# Generated by Django 5.0.3 on 2024-03-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_group', models.CharField(choices=[('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Seafood', 'Seafood'), ('Bakery', 'Bakery')], max_length=100)),
                ('unit_of_measurement', models.CharField(choices=[('Box', 'Box'), ('Pallet', 'Pallet'), ('Carton', 'Carton'), ('Each', 'Each'), ('kg', 'Kg')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price_without_vat', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_without_vat', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_solution_api.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_rows', to='warehouse_solution_api.request')),
            ],
        ),
    ]
